

export enum recordFormType {
  CHANGE_NAME_PATIENT = 'CHANGE_NAME_PATIENT',
  CHANGE_NAME_DOCTOR = 'CHANGE_NAME_DOCTOR',
  CHANGE_DATE = 'CHANGE_DATE',
  CHANGE_TIME = 'CHANGE_TIME',
  CHANGE_COMPLAINTS = 'CHANGE_COMPLAINTS',
  CHANGE_DOCTOR_FULL_NAME = 'CHANGE_DOCTOR_FULL_NAME',
}
